import { storage } from "./storage";

export async function seedRecipes() {
  const sampleRecipes = [
    {
      title: "Creamy Mushroom Risotto",
      description: "A luxurious and comforting Italian risotto with earthy mushrooms and parmesan cheese",
      cuisine: "Italian" as const,
      dietType: "Vegetarian" as const,
      prepTime: 10,
      cookTime: 30,
      servings: 4,
      ingredients: [
        { name: "Arborio Rice", amount: "1.5", unit: "cups", required: true },
        { name: "Mushrooms", amount: "10", unit: "oz", required: true },
        { name: "Vegetable Broth", amount: "4", unit: "cups", required: true },
        { name: "White Wine", amount: "0.5", unit: "cup", required: false },
        { name: "Parmesan Cheese", amount: "1", unit: "cup", required: true },
        { name: "Butter", amount: "3", unit: "tbsp", required: true },
        { name: "Onion", amount: "1", unit: "medium", required: true },
        { name: "Garlic", amount: "2", unit: "cloves", required: false },
      ],
      instructions: [
        "Clean and slice mushrooms into quarter-inch pieces",
        "Heat vegetable broth in a separate pot until simmering",
        "Sauté diced onion and garlic in butter over medium heat until fragrant",
        "Add sliced mushrooms and cook until golden brown",
        "Stir in the Arborio rice, coating it well with butter",
        "Add white wine and stir until absorbed",
        "Begin adding hot broth one ladle at a time, stirring frequently",
        "Continue adding broth as the rice absorbs it, for about 18-20 minutes",
        "Rice should be creamy but with a slight firmness to the bite",
        "Finish with butter and grated Parmesan cheese",
        "Stir well and season with salt and pepper to taste",
        "Serve immediately in warm bowls",
      ],
      imageUrl: "https://images.unsplash.com/photo-1476124369162-f4978d1a201b?w=500&h=500&fit=crop",
      rating: "4.8",
      tags: ["Italian", "Comfort Food", "Vegetarian", "Elegant"],
    },
    {
      title: "Thai Green Curry",
      description: "Aromatic and spicy Thai curry with coconut milk, fresh herbs, and tender chicken",
      cuisine: "Thai" as const,
      dietType: "Regular" as const,
      prepTime: 15,
      cookTime: 25,
      servings: 4,
      ingredients: [
        { name: "Chicken Breast", amount: "1.5", unit: "lbs", required: true },
        { name: "Coconut Milk", amount: "14", unit: "oz", required: true },
        { name: "Green Curry Paste", amount: "3", unit: "tbsp", required: true },
        { name: "Fish Sauce", amount: "1", unit: "tbsp", required: true },
        { name: "Palm Sugar", amount: "1", unit: "tsp", required: false },
        { name: "Bell Peppers", amount: "2", unit: "medium", required: true },
        { name: "Thai Basil", amount: "0.5", unit: "cup", required: false },
        { name: "Green Chiles", amount: "2", unit: "medium", required: false },
      ],
      instructions: [
        "Cut chicken breast into bite-sized pieces",
        "Heat coconut milk in a large pan over medium-high heat",
        "Stir in green curry paste until well combined",
        "Add chicken pieces and simmer until cooked through, about 12-15 minutes",
        "Add fish sauce and palm sugar",
        "Slice bell peppers and add to the curry",
        "Add sliced green chiles for extra heat",
        "Simmer for another 5-8 minutes until peppers are tender-crisp",
        "Tear fresh Thai basil leaves and stir in just before serving",
        "Taste and adjust seasoning as needed",
        "Serve over jasmine rice",
      ],
      imageUrl: "https://images.unsplash.com/photo-1455619452474-d2be8b1e4e31?w=500&h=500&fit=crop",
      rating: "4.7",
      tags: ["Thai", "Spicy", "Weeknight", "Asian"],
    },
    {
      title: "Mediterranean Quinoa Salad",
      description: "Fresh and healthy salad loaded with quinoa, feta, and crisp vegetables",
      cuisine: "Mediterranean" as const,
      dietType: "Vegan" as const,
      prepTime: 20,
      cookTime: 15,
      servings: 6,
      ingredients: [
        { name: "Quinoa", amount: "1", unit: "cup", required: true },
        { name: "Chickpeas", amount: "1", unit: "can", required: true },
        { name: "Cherry Tomatoes", amount: "2", unit: "cups", required: true },
        { name: "Cucumber", amount: "1", unit: "large", required: true },
        { name: "Red Onion", amount: "0.5", unit: "medium", required: false },
        { name: "Kalamata Olives", amount: "1", unit: "cup", required: false },
        { name: "Fresh Parsley", amount: "0.5", unit: "cup", required: false },
        { name: "Lemon Juice", amount: "3", unit: "tbsp", required: true },
        { name: "Olive Oil", amount: "3", unit: "tbsp", required: true },
      ],
      instructions: [
        "Rinse quinoa under cold water",
        "Cook quinoa according to package directions",
        "Let quinoa cool completely",
        "Halve cherry tomatoes and dice cucumber",
        "Thinly slice red onion",
        "Drain and rinse canned chickpeas",
        "Combine cooled quinoa with chickpeas, tomatoes, cucumber, and onion in a large bowl",
        "Add kalamata olives and fresh parsley",
        "Whisk together lemon juice and olive oil",
        "Pour dressing over the salad and toss well",
        "Season with salt and pepper to taste",
        "Chill until ready to serve",
      ],
      imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=500&fit=crop",
      rating: "4.5",
      tags: ["Mediterranean", "Salad", "Vegan", "Healthy"],
    },
    {
      title: "Spicy Gochujang Chicken Bowl",
      description: "Korean-inspired bowl with marinated chicken, rice, and vibrant vegetables",
      cuisine: "Asian" as const,
      dietType: "Regular" as const,
      prepTime: 15,
      cookTime: 20,
      servings: 2,
      ingredients: [
        { name: "Chicken Thighs", amount: "1", unit: "lb", required: true },
        { name: "Gochujang Paste", amount: "3", unit: "tbsp", required: true },
        { name: "Soy Sauce", amount: "2", unit: "tbsp", required: true },
        { name: "Sesame Oil", amount: "1", unit: "tbsp", required: true },
        { name: "Rice", amount: "2", unit: "cups", required: true },
        { name: "Spinach", amount: "4", unit: "oz", required: false },
        { name: "Carrots", amount: "1", unit: "large", required: true },
        { name: "Egg", amount: "2", unit: "medium", required: false },
      ],
      instructions: [
        "Cook rice according to package directions",
        "Cut chicken thighs into bite-sized pieces",
        "Combine gochujang, soy sauce, and sesame oil in a bowl",
        "Marinate chicken in the mixture for at least 10 minutes",
        "Heat a skillet over high heat and cook marinated chicken until cooked through",
        "Blanch spinach in boiling water and season lightly",
        "Julienne carrots and sauté until tender",
        "Fry eggs to your preference",
        "Divide rice between bowls",
        "Arrange chicken, vegetables, and egg on top",
        "Drizzle with extra sauce if desired",
        "Serve immediately while hot",
      ],
      imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop",
      rating: "4.6",
      tags: ["Korean", "Spicy", "Rice Bowl", "Quick"],
    },
    {
      title: "Baked Lemon Herb Salmon",
      description: "Perfectly baked salmon fillet with fresh lemon and aromatic herbs",
      cuisine: "Mediterranean" as const,
      dietType: "Regular" as const,
      prepTime: 10,
      cookTime: 15,
      servings: 2,
      ingredients: [
        { name: "Salmon Fillets", amount: "2", unit: "fillets", required: true },
        { name: "Lemon", amount: "1", unit: "whole", required: true },
        { name: "Dill", amount: "2", unit: "tbsp", required: true },
        { name: "Thyme", amount: "1", unit: "tbsp", required: false },
        { name: "Garlic", amount: "2", unit: "cloves", required: false },
        { name: "Olive Oil", amount: "2", unit: "tbsp", required: true },
        { name: "Asparagus", amount: "8", unit: "oz", required: true },
        { name: "Sea Salt", amount: "1", unit: "tsp", required: false },
      ],
      instructions: [
        "Preheat oven to 400°F",
        "Pat salmon fillets dry with paper towels",
        "Place salmon on a lined baking sheet",
        "Slice lemon thinly",
        "Mince fresh dill, thyme, and garlic",
        "Drizzle salmon with olive oil",
        "Top with lemon slices and herb mixture",
        "Season with sea salt and pepper",
        "Arrange asparagus around the salmon",
        "Drizzle asparagus with olive oil and season",
        "Bake for 12-15 minutes until salmon flakes easily",
        "Serve immediately with lemon wedges",
      ],
      imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop",
      rating: "4.8",
      tags: ["Seafood", "Mediterranean", "Healthy", "Elegant"],
    },
    {
      title: "Vegan Buddha Bowl",
      description: "Colorful and nutritious bowl packed with roasted vegetables and plant-based protein",
      cuisine: "Mediterranean" as const,
      dietType: "Vegan" as const,
      prepTime: 20,
      cookTime: 30,
      servings: 2,
      ingredients: [
        { name: "Sweet Potato", amount: "1", unit: "large", required: true },
        { name: "Chickpeas", amount: "1", unit: "can", required: true },
        { name: "Kale", amount: "4", unit: "cups", required: true },
        { name: "Tahini", amount: "2", unit: "tbsp", required: true },
        { name: "Lemon Juice", amount: "2", unit: "tbsp", required: true },
        { name: "Avocado", amount: "1", unit: "whole", required: false },
        { name: "Brown Rice", amount: "1", unit: "cup", required: true },
        { name: "Pumpkin Seeds", amount: "0.25", unit: "cup", required: false },
      ],
      instructions: [
        "Cook brown rice according to package directions",
        "Cut sweet potato into cubes and roast at 425°F for 25 minutes",
        "Drain and season chickpeas, roast alongside sweet potato",
        "Massage kale with a bit of lemon juice and olive oil",
        "Make tahini dressing by whisking tahini with lemon juice, garlic, and water",
        "Slice avocado just before serving",
        "Divide rice between two bowls",
        "Arrange roasted vegetables, chickpeas, kale, and avocado on top",
        "Drizzle with tahini dressing",
        "Sprinkle pumpkin seeds for crunch",
        "Serve at room temperature or warm",
      ],
      imageUrl: "https://images.unsplash.com/photo-1609501676725-7186f017a4b8?w=500&h=500&fit=crop",
      rating: "4.7",
      tags: ["Vegan", "Buddha Bowl", "Healthy", "Colorful"],
    },
  ];

  // Check if recipes already exist
  const existingRecipes = await storage.getRecipes();
  if (existingRecipes.length > 0) {
    console.log("Recipes already seeded, skipping");
    return;
  }

  // Seed recipes
  for (const recipe of sampleRecipes) {
    try {
      await storage.createRecipe(recipe);
    } catch (error) {
      console.error("Error seeding recipe:", error);
    }
  }

  console.log(`Successfully seeded ${sampleRecipes.length} recipes`);
}
