import { storage } from "./storage";

export async function seedRecipes() {
  const sampleRecipes = [
    {
      title: "Pani Puri (Gol Gappa)",
      description: "Crispy street snack with hollow puris filled with potatoes, chickpeas, and tangy tamarind water",
      cuisine: "Indian" as const,
      dietType: "Vegetarian" as const,
      prepTime: 20,
      cookTime: 15,
      servings: 4,
      ingredients: [
        { name: "Maida Flour", amount: "1.5", unit: "cups", required: true },
        { name: "Potatoes", amount: "4", unit: "medium", required: true },
        { name: "Chickpeas (cooked)", amount: "1", unit: "cup", required: true },
        { name: "Tamarind Paste", amount: "3", unit: "tbsp", required: true },
        { name: "Cumin Powder", amount: "1", unit: "tsp", required: true },
        { name: "Red Chili Powder", amount: "0.5", unit: "tsp", required: true },
        { name: "Black Salt", amount: "0.5", unit: "tsp", required: false },
        { name: "Fresh Coriander", amount: "0.5", unit: "cup", required: false },
      ],
      instructions: [
        "Make a stiff dough with maida flour and salt, knead well",
        "Let dough rest for 30 minutes",
        "Roll small portions into thin circles",
        "Deep fry puris until they puff up and become crispy",
        "Boil potatoes, cool, and cut into small cubes",
        "Mix boiled chickpeas with cumin powder and chili powder",
        "Make tamarind water by mixing tamarind paste with water and salt",
        "Gently break the top of each puri to create an opening",
        "Stuff puris with potato cubes and chickpeas",
        "Pour tamarind water into each puri",
        "Sprinkle fresh coriander and black salt",
        "Serve immediately while puris are still crispy",
      ],
      imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=500&fit=crop",
      rating: "4.8",
      tags: ["Indian", "Street Food", "Vegetarian", "Snack"],
    },
    {
      title: "Chole Bhature",
      description: "Fluffy deep-fried bread served with spiced chickpea curry - a beloved North Indian street classic",
      cuisine: "Indian" as const,
      dietType: "Vegetarian" as const,
      prepTime: 15,
      cookTime: 40,
      servings: 4,
      ingredients: [
        { name: "All-Purpose Flour", amount: "2", unit: "cups", required: true },
        { name: "Canned Chickpeas", amount: "2", unit: "cans", required: true },
        { name: "Onion", amount: "2", unit: "large", required: true },
        { name: "Tomatoes", amount: "3", unit: "medium", required: true },
        { name: "Ginger-Garlic Paste", amount: "2", unit: "tbsp", required: true },
        { name: "Mustard Seeds", amount: "1", unit: "tsp", required: true },
        { name: "Cumin Seeds", amount: "1", unit: "tsp", required: true },
        { name: "Red Chili Powder", amount: "1", unit: "tsp", required: true },
        { name: "Turmeric Powder", amount: "0.5", unit: "tsp", required: true },
      ],
      instructions: [
        "Make bhature dough with flour, yogurt, salt, and baking powder; let it rise for 2 hours",
        "Heat oil and add mustard and cumin seeds until they splutter",
        "Add ginger-garlic paste and sauté until fragrant",
        "Add onions and cook until golden brown",
        "Add tomatoes and cook until softened",
        "Add turmeric and chili powder, mix well",
        "Add drained chickpeas and simmer for 15 minutes",
        "Season with salt and add fresh cilantro",
        "Heat oil for frying bhature",
        "Roll dough into discs and deep fry until puffed and golden",
        "Serve hot bhature with warm chole curry",
        "Garnish with raw onions and pickle",
      ],
      imageUrl: "https://images.unsplash.com/photo-1585314868745-4c78f0b9e37a?w=500&h=500&fit=crop",
      rating: "4.9",
      tags: ["Indian", "Street Food", "Vegetarian", "Comfort Food"],
    },
    {
      title: "Aloo Tikki",
      description: "Crispy potato patties served with tamarind chutney and mint yogurt sauce",
      cuisine: "Indian" as const,
      dietType: "Vegetarian" as const,
      prepTime: 15,
      cookTime: 20,
      servings: 6,
      ingredients: [
        { name: "Potatoes", amount: "6", unit: "medium", required: true },
        { name: "Green Peas", amount: "1", unit: "cup", required: true },
        { name: "Green Chili", amount: "2", unit: "pieces", required: false },
        { name: "Ginger", amount: "1", unit: "tbsp", required: true },
        { name: "Cumin Seeds", amount: "1", unit: "tsp", required: true },
        { name: "Black Pepper Powder", amount: "0.5", unit: "tsp", required: false },
        { name: "Bread Crumbs", amount: "0.5", unit: "cup", required: true },
        { name: "Fresh Cilantro", amount: "0.5", unit: "cup", required: false },
      ],
      instructions: [
        "Boil potatoes and peas until completely cooked",
        "Mash potatoes while still warm",
        "Finely chop green chili and ginger",
        "Mix chopped green chili, ginger, and cilantro into mashed potatoes",
        "Add cumin seeds and black pepper powder",
        "Season with salt to taste",
        "Make small oval cakes from the mixture",
        "Roll each cake in bread crumbs",
        "Shallow fry in oil on medium heat until golden brown on both sides",
        "Serve hot with tamarind chutney and mint yogurt",
        "Garnish with fresh cilantro",
        "Serve immediately while crispy",
      ],
      imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=500&fit=crop",
      rating: "4.7",
      tags: ["Indian", "Street Food", "Vegetarian", "Appetizer"],
    },
    {
      title: "Tandoori Chicken",
      description: "Succulent chicken marinated in yogurt and spices, roasted in a tandoor until charred and juicy",
      cuisine: "Indian" as const,
      dietType: "Regular" as const,
      prepTime: 30,
      cookTime: 25,
      servings: 4,
      ingredients: [
        { name: "Chicken Pieces", amount: "2", unit: "lbs", required: true },
        { name: "Yogurt", amount: "1", unit: "cup", required: true },
        { name: "Ginger-Garlic Paste", amount: "3", unit: "tbsp", required: true },
        { name: "Red Chili Powder", amount: "2", unit: "tsp", required: true },
        { name: "Turmeric Powder", amount: "0.5", unit: "tsp", required: true },
        { name: "Garam Masala", amount: "1", unit: "tsp", required: true },
        { name: "Lemon Juice", amount: "3", unit: "tbsp", required: true },
        { name: "Oil", amount: "2", unit: "tbsp", required: true },
      ],
      instructions: [
        "Clean and pat dry chicken pieces",
        "Make slits in chicken for better marinade penetration",
        "Mix yogurt with ginger-garlic paste in a bowl",
        "Add red chili powder, turmeric, garam masala, and lemon juice",
        "Coat chicken pieces thoroughly with the marinade",
        "Refrigerate for at least 2 hours or overnight",
        "Preheat oven to 450°F or use a tandoor",
        "Apply oil to tandoor or roasting pan",
        "Thread marinated chicken onto skewers",
        "Roast in tandoor for 20-25 minutes or oven for 25-30 minutes",
        "Turn halfway through for even cooking",
        "Serve hot with lemon wedges and sliced onions",
      ],
      imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500&h=500&fit=crop",
      rating: "4.8",
      tags: ["Indian", "Street Food", "Non-Vegetarian", "Grilled"],
    },
    {
      title: "Butter Chicken (Murgh Makhani)",
      description: "Tender chicken in a creamy, aromatic tomato-based sauce with butter and cream - an iconic Indian curry",
      cuisine: "Indian" as const,
      dietType: "Regular" as const,
      prepTime: 20,
      cookTime: 30,
      servings: 4,
      ingredients: [
        { name: "Chicken Breast", amount: "1.5", unit: "lbs", required: true },
        { name: "Butter", amount: "4", unit: "tbsp", required: true },
        { name: "Heavy Cream", amount: "0.75", unit: "cup", required: true },
        { name: "Tomato Puree", amount: "1", unit: "can", required: true },
        { name: "Ginger-Garlic Paste", amount: "2", unit: "tbsp", required: true },
        { name: "Garam Masala", amount: "1.5", unit: "tsp", required: true },
        { name: "Kasuri Methi", amount: "1", unit: "tsp", required: false },
        { name: "Honey", amount: "1", unit: "tbsp", required: false },
      ],
      instructions: [
        "Marinate chicken in yogurt and spices for at least 1 hour",
        "Grill or pan-fry chicken until cooked through and slightly charred",
        "Cut cooked chicken into bite-sized pieces",
        "Melt butter in a large pan over medium heat",
        "Add ginger-garlic paste and sauté for 1 minute",
        "Add tomato puree and simmer for 5 minutes",
        "Stir in garam masala and cook for another minute",
        "Pour in heavy cream and mix well",
        "Add chicken pieces and simmer for 10 minutes",
        "Add kasuri methi and honey, adjust seasoning",
        "Simmer until sauce reaches desired consistency",
        "Serve hot with naan or rice",
      ],
      imageUrl: "https://images.unsplash.com/photo-1588166524941-3bf0c2ed4d4a?w=500&h=500&fit=crop",
      rating: "4.9",
      tags: ["Indian", "Curry", "Non-Vegetarian", "Creamy"],
    },
    {
      title: "Masala Dosa",
      description: "Crispy rice crepe filled with spiced potato and served with coconut chutney and sambar sauce",
      cuisine: "Indian" as const,
      dietType: "Vegetarian" as const,
      prepTime: 25,
      cookTime: 20,
      servings: 4,
      ingredients: [
        { name: "Rice", amount: "1", unit: "cup", required: true },
        { name: "Urad Dal", amount: "0.25", unit: "cup", required: true },
        { name: "Potatoes", amount: "4", unit: "medium", required: true },
        { name: "Onion", amount: "1", unit: "large", required: true },
        { name: "Green Chili", amount: "2", unit: "pieces", required: false },
        { name: "Mustard Seeds", amount: "1", unit: "tsp", required: true },
        { name: "Curry Leaves", amount: "8-10", unit: "leaves", required: true },
        { name: "Turmeric Powder", amount: "0.5", unit: "tsp", required: true },
      ],
      instructions: [
        "Soak rice and urad dal separately for 4 hours",
        "Grind soaked rice and dal separately into smooth batters",
        "Mix batters together and ferment for 8 hours or overnight",
        "Boil potatoes and cut into small pieces",
        "Heat oil in a pan and add mustard seeds",
        "When seeds splutter, add curry leaves",
        "Add onions and cook until golden",
        "Add green chili, potatoes, and turmeric powder",
        "Cook until potatoes are well mixed with spices",
        "Heat a dosa tawa or non-stick pan over high heat",
        "Spread dosa batter thinly and drizzle oil around edges",
        "Cook until crispy and golden, then flip if needed",
        "Fill with potato curry and fold in half",
        "Serve hot with coconut chutney and sambar",
      ],
      imageUrl: "masala-dosa.jpg",
      rating: "4.7",
      tags: ["Indian", "Street Food", "Vegetarian", "South Indian"],
    },
  ];

  // Delete all existing recipes
  const existingRecipes = await storage.getRecipes();
  for (const recipe of existingRecipes) {
    await storage.deleteRecipe(recipe.id);
  }

  // Seed recipes
  for (const recipe of sampleRecipes) {
    try {
      await storage.createRecipe(recipe);
    } catch (error) {
      console.error("Error seeding recipe:", error);
    }
  }

  console.log(`Successfully seeded ${sampleRecipes.length} recipes`);
}
